# This file was generated by the {rix} R package v0.9.1 on 2024-08-30
# with following call:
# >rix(r_ver = "frozen_edge",
#  > r_pkgs = c("ALDEx2",
#  > "bartMachine",
#  > "basilisk",
#  > "BiocManager",
#  > "BiocVersion",
#  > "biomformat",
#  > "chromote",
#  > "ComplexHeatmap",
#  > "devtools",
#  > "dplyr",
#  > "FSA",
#  > "gbp",
#  > "GGally",
#  > "ggplot2",
#  > "ggpubr",
#  > "glmnet",
#  > "knitr",
#  > "latex2exp",
#  > "MGnifyR",
#  > "miaViz",
#  > "miniUI",
#  > "MOFA2",
#  > "multiview",
#  > "patchwork",
#  > "pheatmap",
#  > "randomForest",
#  > "renv",
#  > "reshape2",
#  > "reticulate",
#  > "rmarkdown",
#  > "shadowtext",
#  > "styler",
#  > "UpSetR",
#  > "vegan",
#  > "xgboost"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(list(package_name = "rix",
#  >      repo_url = "https://github.com/b-rodrigues/rix/",
#  > commit = "008e3d1ac579cbcd4de3b9a2315635c652b687bd"),
#  > list(package_name = "HoloFoodR",
#  > repo_url = "https://github.com/EBI-Metagenomics/HoloFoodR",
#  > commit = "cb26f00d43a060c0cac24f9a339edb27d36ecf85"),
#  > list(package_name = "mia",
#  > repo_url = "https://github.com/microbiome/mia",
#  > commit = "dcaa110131162d48d82081d1da3a74da18268a3b")),
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides bleeding
# edge packages and R.
# Only use bleeding edge packages if absolutely needed!
# Read more on https://b-rodrigues.github.io/rix/articles/z-bleeding_edge.html
# Report any issues to https://github.com/b-rodrigues/rix
let
  pkgs =
    import
      (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/b5cd423a3684307faf822b875cd186e4d7173a10.tar.gz")
      { };

  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      ALDEx2
      bartMachine
      basilisk
      BiocManager
      BiocVersion
      biomformat
      chromote
      ComplexHeatmap
      devtools
      dplyr
      FSA
      gbp
      GGally
      ggplot2
      ggpubr
      glmnet
      knitr
      latex2exp
      MGnifyR
      miaViz
      miniUI
      MOFA2
      multiview
      patchwork
      pheatmap
      randomForest
      renv
      reshape2
      reticulate
      rmarkdown
      shadowtext
      styler
      UpSetR
      vegan
      xgboost
      languageserver
      ;
  };

  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "rix";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rix/";
        rev = "008e3d1ac579cbcd4de3b9a2315635c652b687bd";
        sha256 = "sha256-nrHHiHLYXehly0/qwhGvGmIgJrgyiW4kFIKJ1HvWQfg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          codetools
          curl
          jsonlite
          sys
          ;
      };
    })

    (pkgs.rPackages.buildRPackage {
      name = "HoloFoodR";
      src = pkgs.fetchgit {
        url = "https://github.com/EBI-Metagenomics/HoloFoodR";
        rev = "4440bdf1ed9f25acfc9cc72075b6ae5b08ea9efc";
        sha256 = "sha256-EYqlW/AKb1/7I5krRb+d7H0gjuIXDNhcGyYw9lTX46g=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          TreeSummarizedExperiment
          MultiAssayExperiment
          dplyr
          httr2
          jsonlite
          S4Vectors
          ;
      };
    })

    (pkgs.rPackages.buildRPackage {
      name = "mia";
      src = pkgs.fetchgit {
        url = "https://github.com/microbiome/mia";
        rev = "52d2a236449206f66e8b03ad21e7abe40313c2cf";
        sha256 = "sha256-Y40PB8/rFwite7cvRTbz6qbjj3wEli+M0oFt/qI4Q5E=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          SummarizedExperiment
          SingleCellExperiment
          TreeSummarizedExperiment
          MultiAssayExperiment
          MASS
          ape
          decontam
          vegan
          BiocGenerics
          S4Vectors
          IRanges
          Biostrings
          DECIPHER
          BiocParallel
          DelayedArray
          DelayedMatrixStats
          scuttle
          scater
          DirichletMultinomial
          rlang
          dplyr
          tibble
          tidyr
          bluster
          MatrixGenerics
          mediation
          rbiom
          ;
      };
    })
  ];

  system_packages = builtins.attrValues {
    inherit (pkgs)
      R
      glibcLocales
      nix
      ;
  };

in

pkgs.mkShell {
  LOCALE_ARCHIVE =
    if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
  LC_ALL = "en_US.UTF-8";
  LC_TIME = "en_US.UTF-8";
  LC_MONETARY = "en_US.UTF-8";
  LC_PAPER = "en_US.UTF-8";
  LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [
    git_archive_pkgs
    rpkgs
    system_packages
  ];

}
