# This file was generated by the {rix} R package v0.9.1 on 2024-08-29
# with following call:
# >rix(r_ver = "a6292e34000dc93d43bccf78338770c1c5ec8a99",
#  > r_pkgs = c("ALDEx2",
#  > "BiocManager",
#  > "BiocVersion",
#  > "ComplexHeatmap",
#  > "FSA",
#  > "GGally",
#  > "MGnifyR",
#  > "UpSetR",
#  > "bartMachine",
#  > "basilisk",
#  > "biomformat",
#  > "chromote",
#  > "devtools",
#  > "dplyr",
#  > "gbp",
#  > "ggplot2",
#  > "ggpubr",
#  > "glmnet",
#  > "knitr",
#  > "miaViz",
#  > "miniUI",
#  > "multiview",
#  > "patchwork",
#  > "pheatmap",
#  > "randomForest",
#  > "renv",
#  > "reshape2",
#  > "reticulate",
#  > "rmarkdown",
#  > "shadowtext",
#  > "styler",
#  > "vegan",
#  > "xgboost"),
#  > system_pkgs = c("quarto"),
#  > git_pkgs = list(list(package_name = "rix",
#  >      repo_url = "https://github.com/b-rodrigues/rix/",
#  > commit = "008e3d1ac579cbcd4de3b9a2315635c652b687bd"),
#  > list(package_name = "HoloFoodR",
#  > repo_url = "https://github.com/EBI-Metagenomics/HoloFoodR",
#  > commit = "815071128cdd8e099fbee032dd56fc12a14bfd00"),
#  > list(package_name = "mia",
#  > repo_url = "https://github.com/microbiome/mia",
#  > commit = "dcaa110131162d48d82081d1da3a74da18268a3b")),
#  > ide = "code",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision a6292e34000dc93d43bccf78338770c1c5ec8a99 for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/b-rodrigues/rix

### NOTE ###
# HoloFoodR included R as a dependency, which fails the build process
# because R is not an R package. Thus, this dependency was removed manually
let
  pkgs =
    import
      (fetchTarball "https://github.com/NixOS/nixpkgs/archive/a6292e34000dc93d43bccf78338770c1c5ec8a99.tar.gz")
      { };

  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      ALDEx2
      BiocManager
      BiocVersion
      ComplexHeatmap
      FSA
      GGally
      MGnifyR
      UpSetR
      bartMachine
      basilisk
      biomformat
      chromote
      devtools
      dplyr
      gbp
      ggplot2
      ggpubr
      glmnet
      knitr
      miaViz
      miniUI
      multiview
      patchwork
      pheatmap
      randomForest
      renv
      reshape2
      reticulate
      rmarkdown
      shadowtext
      styler
      vegan
      xgboost
      languageserver
      ;
  };

  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "rix";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rix/";
        rev = "008e3d1ac579cbcd4de3b9a2315635c652b687bd";
        sha256 = "sha256-nrHHiHLYXehly0/qwhGvGmIgJrgyiW4kFIKJ1HvWQfg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          codetools
          curl
          jsonlite
          sys
          ;
      };
    })

    (pkgs.rPackages.buildRPackage {
      name = "HoloFoodR";
      src = pkgs.fetchgit {
        url = "https://github.com/EBI-Metagenomics/HoloFoodR";
        rev = "815071128cdd8e099fbee032dd56fc12a14bfd00";
        sha256 = "sha256-Kwi/2RODbWDcQrHtGTPKox5Nv/LIWBUiTtwMRJjR4Xw=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          TreeSummarizedExperiment
          MultiAssayExperiment
          dplyr
          httr2
          jsonlite
          S4Vectors
          ;
      };
    })

    (pkgs.rPackages.buildRPackage {
      name = "mia";
      src = pkgs.fetchgit {
        url = "https://github.com/microbiome/mia";
        rev = "dcaa110131162d48d82081d1da3a74da18268a3b";
        sha256 = "sha256-fPtt+mdz+2AFYvbRhlOFjRIA/oeTjZIEyV6X0T8NKRc=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          SummarizedExperiment
          SingleCellExperiment
          TreeSummarizedExperiment
          MultiAssayExperiment
          MASS
          ape
          decontam
          vegan
          BiocGenerics
          S4Vectors
          IRanges
          Biostrings
          DECIPHER
          BiocParallel
          DelayedArray
          DelayedMatrixStats
          scuttle
          scater
          DirichletMultinomial
          rlang
          dplyr
          tibble
          tidyr
          bluster
          MatrixGenerics
          mediation
          rbiom
          ;
      };
    })
  ];

  system_packages = builtins.attrValues {
    inherit (pkgs)
      quarto
      R
      glibcLocales
      nix
      ;
  };

in

pkgs.mkShell {
  LOCALE_ARCHIVE =
    if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
  LC_ALL = "en_US.UTF-8";
  LC_TIME = "en_US.UTF-8";
  LC_MONETARY = "en_US.UTF-8";
  LC_PAPER = "en_US.UTF-8";
  LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [
    git_archive_pkgs
    rpkgs
    system_packages
  ];

}
