---
title: "case_study_trial_b"
format: html
---

```{r}
# Read MAE object
mae <- readRDS("../inst/extdata/salmon_mae.RDS")

# Filter trial B
mae <- mae[, colData(mae)[["Trial code"]] == "SB", ]

# Fetch only experiments that we need
mae <- mae[, , c("FATTY ACIDS MG", "metagenomic_assembly")]
```

```{r}
# Check what data is availabe in this mae object
names(mae)
```

## MOFA2

```{r}
# From metabolite data, remove organ-fatty acids row as it only contains a
# string value "muscle"
tse <- mae[[1]]
tse <- tse[!(rowData(tse)[["marker.name"]] %in% c("Organ-fatty acids")), ]
mae[[1]] <- tse

# Transform matrices to numeric. There are some values that are "< 0.01".
# If a number is < 0.01, assume it to be 0.
assay <- assay(mae[[1]], "counts")
assay[ assay == "<0.01" ] <- 0
assay <- apply(assay, c(1, 2), function(x) as.numeric(gsub(",", ".", x)))

# Reassign assay back to MAE
assay(mae[[1]], "counts") <- assay

# From metagenomics data, remove those rows that do not have taxonomy info
not_empty <- !apply(rowData(mae[[2]]), 1, function(x) all(is.na(x)))
mae[[2]] <- mae[[2]][ not_empty, ]


# Transform fatty acids in mg with log10
mae[[1]] <- transformAssay(
    mae[[1]],
    assay.type = "counts",
    MARGIN = "samples",
    method = "log10",
    pseudocount = TRUE
)

# Agglomerate metagenomics data to Genus level and add it to altExp slot
rank <- "Genus"
altExp(mae[[2]], rank) <- agglomerateByRank(mae[[2]], rank)

# Transform microbiome with centered log-ratio method
altExp(mae[[2]], rank) <- transformAssay(
    altExp(mae[[2]], rank), method = "relabundance")
altExp(mae[[2]], rank) <- transformAssay(
    altExp(mae[[2]], rank), assay.type = "relabundance", method = "clr", pseudocount = TRUE)
```

```{r}
# Replace original data with agglomerated one
mae_sub <- mae
mae_sub[[2]] <- altExp(mae_sub[[2]], rank)
```

```{r}
# Rename column names to make them more consistent
names(colData(mae_sub)) <- tolower(gsub(" ", "_", names(colData(mae_sub))))

# Add salmon host mass to colData
merged_coldata <- merge(x = colData(mae_sub), y = colData(mae_sub[[2]])[c("animal", "host.gutted.mass")], all.x = TRUE, by = "animal")
rownames(merged_coldata) <- merged_coldata$animal
colData(mae_sub) <- merged_coldata

# Add mass categories
mass_median <- median(colData(mae_sub)[, "host.gutted.mass"])
colData(mae_sub)["mass_category"] <- ifelse(
  colData(mae_sub)[, "host.gutted.mass"] > mass_median, "heavy", "light")

# Add control vs treatment groups
colData(mae_sub)["treatment_group"] <- ifelse(
  colData(mae_sub)[, "treatment_concentration"] == 0, "control", "treatment")

# Select only the column we require
colData(mae_sub) <- colData(mae_sub)[ , c("treatment_code", treatment_group, "host.gutted.mass", "mass_category"), drop = FALSE]

# Create MOFA model
model <- create_mofa_from_MultiAssayExperiment(
    mae_sub,
    extract_metadata = TRUE
)

# Set model's options
model_opts <- get_default_model_options(model)
model_opts$num_factors <- 7
train_opts <- get_default_training_options(model)

# Change convergence mode to slightly improve accuracy
train_opts$convergence_mode <- "slow"

# Prepare MOFA model
model <- prepare_mofa(
  object = model,
  model_options = model_opts
)

# Train model
model <- run_mofa(model, use_basilisk = TRUE)
```

```{r}
#| fig-width: 10
plot_factor_cor(
  model,
  method = "pearson",
  cl.ratio = 0.2,
  tl.srt = 0,
  title = "Pearson correlation between factors",
  mar=c(0, 0, 2, 0),
)
```

```{r}
# Get variance explained
var_explained <- get_variance_explained(model)

# Get total variance explained
var_explained_total <- as.data.frame(
  var_explained$r2_total$group1
)

# Get variance by factor
var_explained_factor <- as.data.frame(var_explained$r2_per_factor$group1)

# Change column names and add view names for clarity
colnames(var_explained_total) <- "var_explained"
var_explained_total["view"] <- rownames(var_explained_total)

colnames(var_explained_factor) <- c("fatty_acids", "metagenomic_assembly")
var_explained_factor["factor"] <- rownames(var_explained_factor)

# Melt dataframe for plotting
var_explained_factor_melt <- melt(
  var_explained_factor,
  id.vars = "factor",
  measure.vars = c("fatty_acids", "metagenomic_assembly"))
```

```{r}
ggplot(
  data = var_explained_total,
  aes(x = view, y = var_explained, fill = view)
) +
  geom_bar(stat = "identity") +
  labs(title = "Variance explained by view", x = "View", y = "Variance explained") +
  scale_x_discrete(labels = c("Fatty acids", "Metagenomics")) + # Custom x-axis ticks
  theme_minimal() +
  theme(
    plot.title.position = "plot", # Align title position with plot
    legend.position = "none"
  )
```

